### ISSUE TITLE
Decide Architecture, integrate redux and PWA.

### ISSUE THREAD

**Issue by KishanBusa8** [marksolutions/react-movies#1]
This web application must have PWA architecture. So all checks for PWA must be passed. See the ref. https://web.dev/progressive-web-apps/

TODO

- [x] add Support TypeScript
- [x] add Support Redux Store
- [x] add Support Router

**Comment by bhi10** [comment]
I have some suggestions for project architecture. I think we should use **The View-State Split** architecture.

Let me know your thoughts on the same.
